name: Deploy Logic App
on: workflow_dispatch 
# on: 
#   push:
#     branches:
#         - main
#     paths:
#         - '**.json'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    #Log into Azure
    - uses: azure/login@v1
      with:
           creds: '{"clientId":"${{ secrets.ACTION_SPN_CLIENTID }}","clientSecret":"${{ secrets.ACTION_SPN_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    # Deploy Logic App ARM Template
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: 'prg-synapse-dp'
        deploymentName: 'logicapp-synapse-sqlpool_deployment'
        template: 'logicaapp-synapse-sqlpool/pause-resume-scale/LogicApp.json'
        parameters: 'logicaapp-synapse-sqlpool/pause-resume-scale/LogicApp.parameters.json'
        failOnStdErr: false
